coded file
Szpytowski/for-each pull request #1
Opened 2024-11-24 19:13 UTC by Szpytowski

2024-11-25 17:17 UTC, Solnick requested changes

2024-11-25 17:17 UTC, Solnick commented on js/app.js
> +  return Math.floor(averageScore);
Why do you want to use the number rounding here?

2024-11-25 20:44 UTC, Szpytowski commented on js/app.js
> +  return Math.floor(averageScore);
I was thinking in terms of the polish points system, "trojka, czworka ..." and wanted to round it up. I changed it

2024-11-26 11:36 UTC, Solnick requested changes

2024-11-26 11:36 UTC, Solnick commented on js/app.js
> +  return (averageScore);
```suggestion
  return totalScore / marks.length;
```

2024-11-26 11:36 UTC, Solnick commented on js/app.js
> +  let positiveNumbers = [];
can be const

2024-11-26 11:36 UTC, Solnick commented on js/app.js
> +let marksArray = [4, 5, 3, 4, 5];
can be const

2024-11-26 14:14 UTC, Solnick approved these changes

2024-11-26 14:15 UTC, merged